name: Unit tests
on: push
jobs:
  build:
    runs-on: ubuntu-24.04
    name: Vite ${{ matrix.vite }} / Node ${{ matrix.node }}
    strategy:
      matrix:
        node: [18,20,22]
        vite: [4,5,6]
    env:
      VITE_VERSION: ${{ matrix.vite }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout PR branch
        uses: actions/checkout@v1
      - run: npm install
      - run: bin/ci-install.sh
      - run: npm test
