name: Unit tests
on: push
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node: [22] 
        vite: [6] # 4,5,6 still supported
    env:
      VITE_VERSION: ${{ matrix.vite }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout PR branch
        uses: actions/checkout@v1
      - run: npm ci
      - run: bin/ci-install.sh
      - run: npm test
